/* SPDX-License-Identifier: LicenseRef-Edgron-Source-Available
 * Copyright (c) 2026 Edgron. See LICENSE at the SDK root. */
/* app_user_cm4.c — YOUR application on the CM4 (real-time) core.
 *
 * The counterpart of CM7/App/app_user.c. Nothing under App/ is regenerated by CubeMX, so this
 * file is yours. The platform calls app_user_cm4_init() once, before the CM4 main loop starts;
 * create your own thread(s) there.
 *
 * WHICH CORE SHOULD YOUR CODE GO ON?
 *   CM4 (here)  — reacts in microseconds: interlocks, pulse-driven logic, anything that must
 *                 not wait behind the network stack. This core owns the field buses and the
 *                 onboard high-speed inputs, so the data is freshest here.
 *   CM7         — everything else: cloud, dashboard, storage, recipes, scheduling, UI.
 *
 * Both cores use the SAME API names on the SAME process image (app_platform_cm4.h mirrors
 * app_platform.h), so a piece of logic can be moved from one core to the other unchanged —
 * this file is a live example of exactly that.
 */
#include "cmsis_os.h"
#include "app_platform_cm4.h"
#include "app_user_points.h"   /* the same point names CM7 uses — no hand-kept indexes */

/* This interlock used to live in the CM7 control task. It was moved here because it is a
 * direct input-to-output reaction: an input edge must flip the relay without waiting behind
 * anything the network core happens to be doing. The other four inputs still toggle their
 * relays from CM7 — both cores drive the same relay module through the process image, and the
 * platform's locking keeps them from stepping on each other. */
/* RETIRED 2026-09-03: the demo flipped relay 12 on every HSDI1 rising edge. HSDI0~3 are pulse
 * counters (water meter on HSDI0) and HSDI4~7 gutter level sensors on this installation —
 * no onboard input may drive an output here. The skeleton stays as the pattern for a real
 * interlock: read app_hsdi_level(), react with app_io_do_set(), osDelay(5) for a 5 ms loop. */
#if 0
#define TOGGLE_IN   1U   /* HSDI channel 1 */
#define TOGGLE_OUT  12U

static void interlock_task(void *arg)
{
  uint8_t prev = 0;
  (void)arg;
  for (;;)
  {
    uint8_t lv = app_hsdi_level(TOGGLE_IN);
    if (lv && !prev)                        /* rising edge (already debounced by the driver) */
    {
      app_io_do_set(PT_RELAY, TOGGLE_OUT, (uint8_t)!app_io_do_get(PT_RELAY, TOGGLE_OUT));
    }
    prev = lv;
    osDelay(5);                             /* 5 ms reaction; tighten if your process needs it */
  }
}
#endif

void app_user_cm4_init(void)
{
  /* nothing to start on this installation (see above); a real interlock task would be
   * created here with osThreadNew(interlock_task, NULL, &attr). */
}
