/* SPDX-License-Identifier: LicenseRef-Edgron-Source-Available
 * Copyright (c) 2026 Edgron. See LICENSE at the SDK root. */
/* app_certs.h — TLS trust anchors and device identity (declarations; this file holds no secrets, safe to commit)
 * The concrete app_certs.c is generated by CMake at build time from the PEMs in keys/ca/ into the build directory——
 * the device private key never enters the source tree, never enters git history
 * Architecture convention: trust anchor (ca) travels with the deployment (can be OTA-updated / cloud-switched later); device identity travels with the board (production board migrates to ATECC608B) */
#ifndef APP_CERTS_H
#define APP_CERTS_H
#include <stddef.h>

extern const char app_tls_ca_pem[];        /* Trust anchor: Edgron Root CA certificate */
extern const char app_tls_devcert_pem[];   /* Device certificate (public) */
extern const char app_tls_devkey_pem[];    /* Device private key placeholder; the real per-device key lives inside the ATECC608A */
extern const char app_fwsign_pub_pem[];    /* Firmware signature verification public key (public; private key signs on PC) */
extern const char app_anticlone_pub_pem[]; /* Anti-clone verification public key (public; private key in 608B/dev_se) */
extern const char app_se_dev_key_pem[];    /* Software SE emulation private key (dev only, not in production board) */
extern const char app_aws_ca_pem[];        /* AWS trust anchor: Amazon Root CA 1 (verify server when connecting to AWS) */
/* mbedTLS requires PEM length to include the trailing NUL, provided with sizeof semantics */
extern const size_t app_tls_ca_len, app_tls_devcert_len, app_tls_devkey_len, app_fwsign_pub_len;
extern const size_t app_anticlone_pub_len, app_se_dev_key_len, app_aws_ca_len;

#endif
