/* SPDX-License-Identifier: LicenseRef-Edgron-Source-Available
 * Copyright (c) 2026 Edgron. See LICENSE at the SDK root. */
/* app_user.c — YOUR application lives here.
 *
 * This is a user file: nothing under App/ is ever regenerated by CubeMX, so your code is safe.
 *
 * The file is deliberately split into three parts:
 *   1. CONFIGURATION TABLES — describe your hardware here. This is normally all you edit.
 *   2. YOUR CONTROL LOGIC   — your application tasks.
 *   3. STARTUP              — generic wiring; you rarely need to touch it.
 *
 * Platform services are in app_platform.h:
 *   - Process-image I/O (cyclic, non-blocking):  app_io_setup() then app_io_di/ai/do_set/hr_set()
 *   - Onboard high-speed inputs (CN4):           app_hsdi_setup() then app_hsdi_level/count/...
 *   - On-demand Modbus master (blocking):        app_mb_read_holding/read_input/write_single/...
 *   - Backplane expansion modules:               any of the above, port = APP_PORT_BACKPLANE
 *   - Time / temperature / buzzer:               app_time_now() / app_temp_read() / app_beep_set()
 *   - Power-fail retained variables:             mark them PF_RETAIN (see app_pwrfail.h)
 */
#include "app_user.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "app_platform.h"
#include "app_user_points.h"   /* the point names, shared with the CM4 side */
#include "app_vent.h"          /* greenhouse roof-vent temperature control */
#include "app_flowmon.h"       /* per-gutter feed-flow monitor / blocked-line alarm */
#include "app_dose.h"          /* nutrient/pH dosing pumps (relay coils 0..2) */
#include "app_aer.h"           /* reservoir aeration: air pump on relay coil 8, by water temperature */
#include "FreeRTOS.h"
#include "task.h"

/* ==========================================================================================
 * 1. CONFIGURATION TABLES — describe your hardware here
 * ========================================================================================== */

/* ---- 1a. Field devices polled over Modbus (the process-image scan table) ----
 * Three devices on the 485A port. The CM4 scanner polls them in the background and keeps their
 * data in the process image; your code and any external master then just read/write memory.
 *   addr 1 : 12 digital inputs + 8 digital outputs
 *   addr 2 : 8 x 16-bit analog inputs
 *   addr 3 : 8 x 16-bit analog outputs
 * `start` = the address inside that device (from its manual). `period` = poll interval in base
 * ticks (1 tick = 1 ms).
 *
 * PICK PERIODS THAT MATCH THE PHYSICS, not the fastest the bus allows. A relay does not need
 * a 1 ms refresh — asking for one just saturates the bus (its TX LED goes solid) and starves
 * every other module. 20 ms for digital, 50..100 ms for relays and analog is plenty; this is
 * also how you budget bus bandwidth between modules. */
static app_io_point_t s_io_table[] = {   /* size comes from the rows below, so the check is real
                                          * (RAM: the bench `pulse` command shortens the relay period) */
  /* port,          addr, access,             flags, start, count, period */
  { APP_PORT_485A,  1,    APP_IO_IN_DISCRETE, 0,     0,     12,    20  },  /* PT_DI: 12 DI  <- FC02 */
  { APP_PORT_485A,  2,    APP_IO_IN_INPUT_REG,0,     0,     8,     100 },  /* PT_AI:  8 AI  <- FC04 */
  { APP_PORT_485A,  1,    APP_IO_OUT_COILS,   0,     0,     8,     20  },  /* PT_DO:  8 DO  -> FC15 */
  { APP_PORT_485A,  3,    APP_IO_OUT_HOLDING, 0,     0,     8,     100 },  /* PT_AO:  8 AO  -> FC16 */
  /* A 16-channel relay module on the internal backplane at DIP address 2. The backplane is
   * plain Modbus, so it is just two more rows: one to drive the relays, one to read their real
   * state back (FC01) rather than trusting the commanded value. */
  { APP_PORT_BACKPLANE, 2, APP_IO_OUT_COILS,   0,     0,     16,    50  },  /* PT_RELAY:    drive 16 relays */
  { APP_PORT_BACKPLANE, 2, APP_IO_IN_COILS,    0,     0,     16,    100 },  /* PT_RELAY_RB: true read-back */
  /* PH_EC engineering block (module spec §2, 0x0108: ph1,ph2,ec1,ec2,t1..t4 x0.1/0.01):
   * the vent controller (app_vent.c) reads air temperature t2 from here. 1 s is plenty
   * for a thermal process and costs the backplane next to nothing. */
  { APP_PORT_BACKPLANE, 4, APP_IO_IN_INPUT_REG,0,     0x0108,8,     1000 }, /* PT_PHEC: pH/EC/temps */
};
/* Add a row above and a name in app_user_points.h, in the same order — this catches forgetting
 * either side at build time instead of silently addressing the wrong point at run time. */
_Static_assert(sizeof(s_io_table) / sizeof(s_io_table[0]) == PT_COUNT,
               "s_io_table and the point names in app_user_points.h are out of sync");

/* The "input edge toggles a relay" demo is GONE (2026-09-03): HSDI4~7 now carry the four
 * gutter level sensors and HSDI0 the water meter -- on this installation no onboard input
 * may ever drive an output. (Its CM4 twin, HSDI1 -> relay 12 in app_user_cm4.c, was retired
 * the same day.) Inputs are read below and published; the control logic decides. */

/* ---- 1b. Onboard high-speed digital inputs (the 8 channels on CN4) ----
 * As shipped: SEVEN pulse counters + one plain input (2026-09-01: one pulse flow meter per
 * irrigation line — a clogged line shows up as a stalled counter). Hardware counters sit on
 * HSDI0/4/6, the only channels that can clock their timer (TIM3 / TIM1 / TIM8, one counter
 * per timer); HSDI1/2/3/5 count in software (EXTI edges, fine for <=10 kHz pulse sensors,
 * debounce 0 because a hall flow sensor is an electronic signal). HSDI7 stays a plain input:
 * it shares EXTI0 with HSDI2 and only one of that pair may count — seven counters is this
 * board's silicon ceiling.
 *
 * For two quadrature encoders instead, change the rows to:
 *   HSDI0 = ENC_A, HSDI1 = ENC_B, HSDI2 = ENC_Z   -> encoder 0 (TIM3)
 *   HSDI4 = ENC_A, HSDI5 = ENC_B, HSDI3 = ENC_Z   -> encoder 1 (TIM1)
 *   HSDI6 = COUNT_HW, HSDI7 = COUNT_SW
 * Two encoders AND three hardware counters is not possible — the encoders consume TIM3 and
 * TIM1, leaving only TIM8. An unrealisable table is rejected at startup and every channel
 * falls back to a plain input. Full combination table: HSDI_Configuration_and_Counting.md */
static app_hsdi_ch_t s_hsdi_table[8] = {   /* RAM copy: `hsdi <ch> <mode> ...` re-modes a channel at run time (bench) */
  /* mode,               filter, edge,                 z_action, debounce_ms, min_us */
  { APP_HSDI_COUNT_CAP,  15, APP_HSDI_EDGE_RISING,  0,        0,  1000 },  /* HSDI0  water meter: same hall type as the gutter meters,
                                                                           * same treatment (was a TIM3 hardware counter, filter 4) */
  { APP_HSDI_DI,         0,  0,                     0,        10, 0    },  /* HSDI1  spare (PC7) */
  { APP_HSDI_DI,         0,  0,                     0,        10, 0    },  /* HSDI2  spare (PB0) */
  { APP_HSDI_DI,         0,  0,                     0,        10, 0    },  /* HSDI3  spare (PB1) */
  /* HSDI4~7 = per-gutter hall flow meters 1~4 (2026-09-03, 1200 p/L; terminals 2/4, 7/9, 8/10, 12/14).
   * Capture counters with the pulse qualifier (2026-09-04): both edges are timestamped in the
   * timer capture interrupt and a level counts only after it has held min_us = 1000 us. The
   * 15 ms meter pulses carry microsecond dips that made every plain edge method (EXTI, ICF15
   * capture, timer external clock) read 1.5..2x; the qualifier reads what 1 kHz sampling and
   * the measuring jug read (1.4/1.5/1.3/1.5 L/min, 2026-09-04). What the edge recorder
   * found the same day: the dirt is ~97 kHz oscillation bursts (edges 5 us apart, 1..8 ms
   * long) on the gutter-2 line, plus the sub-microsecond blips it couples into the other
   * three lines. filter 15 (~1 us) removes the blips, min_us drops the bursts, the storm
   * breaker bounds the interrupt load. min_us 3000: a 21 s recording showed chatter phases
   * up to 925 us, too close to 1000; a gutter runs ~30 Hz (16 ms phases), 3000 still allows
   * 166 Hz = 8 L/min. The 1 kHz sampler over-counts those 0.5..1 ms glitches by 1..3 %,
   * so cnt slightly below poll in `hsdi <ch> stat` is the qualifier being right.
   * No EXTI line is used, so HSDI7 no longer collides with HSDI2 on EXTI0. */
  { APP_HSDI_COUNT_CAP,  15, APP_HSDI_EDGE_RISING,  0,        0,  3000 },  /* HSDI4  gutter 1 flow (TIM1_CH1) */
  { APP_HSDI_COUNT_CAP,  15, APP_HSDI_EDGE_RISING,  0,        0,  3000 },  /* HSDI5  gutter 2 flow (TIM1_CH2, terminals 7/9) */
  { APP_HSDI_COUNT_CAP,  15, APP_HSDI_EDGE_RISING,  0,        0,  3000 },  /* HSDI6  gutter 3 flow (TIM8_CH2) */
  { APP_HSDI_COUNT_CAP,  15, APP_HSDI_EDGE_RISING,  0,        0,  3000 },  /* HSDI7  gutter 4 flow (TIM8_CH3) */
};

/* ---- 1c. Ports ---- */
#define CFG_FIELD_PORT   APP_PORT_485A   /* where the field devices above are wired */
#define CFG_FIELD_BAUD   9600
#define CFG_HMI_PORT     APP_PORT_485B   /* where an HMI / SCADA reads the same data (slave) */
#define CFG_HMI_ADDR     10              /* must not clash with the field device addresses */

/* ==========================================================================================
 * 2. YOUR CONTROL LOGIC — reads and writes memory, never blocks on the bus
 * ========================================================================================== */
static void flow_topup_poll(uint32_t cnt); /* water-meter top-up ledger (flow section below) */

static volatile int8_t s_pulse_coil = -1;   /* bench pulse source, see `pulse` below */

static void control_task(void *arg)
{
  (void)arg;
  for (;;)
  {
    /* --- read the field (kept fresh in the background by the scanner) --- */
    uint8_t  start_button = app_io_di(PT_DI, 0);
    uint16_t level        = app_io_ai(PT_AI, 0);

    /* --- read the onboard high-speed inputs --- */
    uint32_t flow_pulses  = app_hsdi_count(0);      /* HSDI0 hardware counter */
    uint8_t  limit_switch = app_hsdi_level(1);      /* HSDI1 plain input */
    flow_topup_poll(flow_pulses);                   /* water-meter top-up ledger (below) */

    /* (the HSDI-edge-toggles-relay demo used to sit here; retired 2026-09-03, see 1b) */

    /* --- bench pulse source (`pulse <coil>`): toggle one relay every control tick = 25 Hz
     * square wave, the same order of magnitude as the greenhouse flow meters that trip the
     * UNNAMED reset. Wire that relay's contact so it switches 24 V into an HSDI A/B pair. --- */
    /* (relay toggling moved to pulse_task, 1 ms resolution — see `pulse` below) */

    /* --- your logic --- */
    uint8_t  pump_on  = (start_button && !limit_switch && (level < 500U)) ? 1U : 0U;
    uint16_t valve_sp = (flow_pulses > 10000UL) ? 0U : 4000U;

    /* --- drive the field --- */
    app_io_do_set(PT_DO, 0, pump_on);
    app_io_hr_set(PT_AO, 0, valve_sp);

    if (app_io_ok(PT_AI) == 0) { /* ... that device is not answering ... */ }

    vTaskDelay(pdMS_TO_TICKS(20));   /* your control rate, independent of the bus scan rate */
  }
}

/* ---- what this application publishes to the cloud dashboard ----
 * The platform's cloud code asks the application for its values instead of hardcoding point
 * indexes, so the dashboard follows your table rather than the other way round. */
uint8_t  app_demo_hsdi_bits(void)          /* 8 input levels as one byte */
{
  uint8_t b = 0;
  /* only the plain-input channels: a pulse channel's level flickers every tick and would turn
   * the cloud's report-on-change into a heartbeat storm (2026-09-03, four flow meters) */
  for (uint8_t i = 0; i < 8U; i++)
  {
    if ((s_hsdi_table[i].mode == APP_HSDI_DI) && app_hsdi_level(i)) { b |= (uint8_t)(1U << i); }
  }
  return b;
}
uint32_t app_demo_count(uint8_t idx)       /* heartbeat c0..c4 = HSDI0 (water meter) then the four
                                            * gutter flow meters HSDI4/5/6/7 (2026-09-03) */
{
  static const uint8_t ch[5] = { 0, 4, 5, 6, 7 };   /* c2 = HSDI5 (gutter 2 meter on terminals 7/9 lands there, 2026-09-03 evening) */
  return (idx < 5U) ? app_hsdi_count(ch[idx]) : 0U;
}

/* ---- bench test commands (2026-09-03 evening, UNNAMED-reset reproduction) ----
 *   pulse <coil 4..16> | pulse off      relay toggles every 20 ms (25 Hz); coils 1..3 are the
 *                                       dosing pumps and are refused
 *   hsdi <ch 0..7> off|di|hw [icf]|poll  re-mode one HSDI channel live (same validator as boot)
 *   hsdi <ch> cap [icf] [min_us]         capture counter (default icf 15, min_us 1000)
 *   hsdi <ch> sw [min_us]                EXTI counter (default min_us 0 = every edge)
 *   hsdi <ch> stat                       signal statistics (CM4 op 0x11)
 *   hsdi rec <mask hex|all> [n]          arm the edge recorder (n entries, max 2048)
 *   hsdi rec stat | hsdi rec get         recorder status / stream it to up/hsdirec/<seq>
 * Cloud: dn/cmd, result rides "cmdr". USB console: same words. */

/* Bench relay square wave: a 1 ms task toggles one coil every `half` ms; while active the
 * PT_RELAY scan row is re-armed at a 5 ms period (default 50) so the backplane actually
 * carries the edges (the scanner writes coils every period, not on change). 2026-09-03:
 * the user wanted the oscilloscope to say how fast the PhotoMOS path really goes. */
static volatile uint16_t s_pulse_half = 0;
static TaskHandle_t s_pulse_task = NULL;
static void pulse_task(void *arg)
{
  uint8_t ph = 0;
  (void)arg;
  for (;;)
  {
    uint16_t half = s_pulse_half;
    if ((s_pulse_coil >= 0) && (half != 0U))
    {
      ph ^= 1U;
      app_io_do_set(PT_RELAY, (uint16_t)s_pulse_coil, ph);
      vTaskDelay(pdMS_TO_TICKS(half));
    }
    else { vTaskDelay(pdMS_TO_TICKS(20)); }
  }
}
static void pulse_scan_period(uint16_t p)
{
  s_io_table[PT_RELAY].period = p;
  (void)app_io_setup(s_io_table, (uint16_t)(sizeof(s_io_table) / sizeof(s_io_table[0])), 1);
}
static void pulse_start(uint8_t coil, uint16_t half_ms)
{
  if (half_ms == 0U) { half_ms = 1U; }
  if (s_pulse_task == NULL) { xTaskCreate(pulse_task, "pulse", 512, NULL, tskIDLE_PRIORITY + 2, &s_pulse_task); }
  pulse_scan_period(1);                     /* 1 ms coil writes: the 5 ms scan aliased against the 5 ms toggle and swallowed ~2% of edges */
  s_pulse_half = half_ms;
  s_pulse_coil = (int8_t)coil;
}
static void pulse_stop(void)
{
  s_pulse_coil = -1; s_pulse_half = 0;
  pulse_scan_period(50);
}

int app_pulse_cmd(const char *line, const char *src, char *out, uint16_t cap)
{
  (void)src;
  if (strncmp(line, "pulse", 5) != 0) { return 0; }
  const char *a = line + 5;
  while (*a == ' ') { a++; }
  if (strncmp(a, "off", 3) == 0) { pulse_stop(); snprintf(out, cap, "pulse off (relay scan 50ms)"); return 1; }
  if (strncmp(a, "sw", 2) == 0)              /* pulse sw <exti line 0..15> <hz>: CM4 fires the line from software (0 hz = off) */
  {
    int line = atoi(a + 2);
    const char *h = strchr(a + 3, ' ');
    int hz = (h != NULL) ? atoi(h + 1) : 0;
    uint16_t period = (hz > 0) ? (uint16_t)((hz >= 1000) ? 1U : (1000U / (unsigned)hz)) : 0U;
    uint8_t req[4] = { 0x13U, (uint8_t)line, (uint8_t)(period & 0xFFU), (uint8_t)(period >> 8) }, rsp[4];
    extern uint16_t app_rpc_transact(const uint8_t *, uint16_t, uint8_t *, uint16_t, uint32_t);
    uint16_t r = app_rpc_transact(req, 4, rsp, sizeof rsp, 100);
    snprintf(out, cap, "pulse sw line%d %s (rpc %s)", line, period ? "on" : "off", r ? "ok" : "no-reply");
    if (period) { snprintf(out + strlen(out), cap - strlen(out), " %uHz", 1000U / period); }
    return 1;
  }
  {
    int coil = atoi(a);
    const char *h = strchr(a, ' ');
    int hz = (h != NULL) ? atoi(h + 1) : 25;
    if ((coil < 4) || (coil > 16)) { snprintf(out, cap, "pulse: coil 4..16 (1..3 = dosing pumps) [hz] | off"); return 1; }
    if (hz < 1) { hz = 1; }
    if (hz > 500) { hz = 500; }
    pulse_start((uint8_t)(coil - 1), (uint16_t)(500U / (unsigned)hz));   /* half-period in ms */
    snprintf(out, cap, "pulse O%d %uHz (relay scan 1ms)", coil, (unsigned)(500U / (500U / (unsigned)hz)));
  }
  return 1;
}
/* ---- HSDI edge recorder dump (2026-09-04): pull the CM4 edge log over RPC (op 0x12) in 60-entry
 * slices and stream it as text to up/hsdirec/<seq> in ~1 KB chunks (the logget uplink slot).
 * Header "HSDIREC n=.. mask=0x.. cyc_us=.. lim=..", then one edge per line
 * "<t_us>,<ch>,<level>,<ccr>,<flags>" (t relative to the first edge, 3 decimals), "END" last.
 * Reader: tools/hsdi_rec.py (fetch + phase analysis + plot). */
static TaskHandle_t s_rec_task = NULL;
static volatile uint16_t s_rec_chunks = 0;
static void rec_send(const char *b, uint16_t n, uint16_t seq)
{
  extern int     app_mqtt_pub_updata(const char *sub, const void *data, uint16_t len);
  extern uint8_t app_mqtt_pub_updata_busy(void);
  extern int8_t  app_mqtt_pub_updata_result(void);
  char sub[24];
  snprintf(sub, sizeof sub, "hsdirec/%u", (unsigned)seq);
  for (int tries = 0; tries < 50; tries++)
  {
    while (app_mqtt_pub_updata_busy()) { vTaskDelay(pdMS_TO_TICKS(20)); }
    if (app_mqtt_pub_updata(sub, b, n) == 0)
    {
      while (app_mqtt_pub_updata_busy()) { vTaskDelay(pdMS_TO_TICKS(20)); }
      if (app_mqtt_pub_updata_result() == 0) { s_rec_chunks++; vTaskDelay(pdMS_TO_TICKS(150)); return; }
    }
    vTaskDelay(pdMS_TO_TICKS(300));
  }
}
static void rec_dump_task(void *arg)
{
  extern uint16_t app_rpc_transact(const uint8_t *, uint16_t, uint8_t *, uint16_t, uint32_t);
  static char    chunk[1100];
  static uint8_t rsp[496];
  uint16_t fill = 0, seq = 0, n = 0, idx = 0;
  uint32_t t0 = 0, cyc_us = 240;
  uint8_t  first = 1, fails = 0;
  (void)arg;
  {
    uint8_t req[2] = { 0x12U, 1U };
    if (app_rpc_transact(req, 2, rsp, sizeof rsp, 100) == 8U)
    {
      n = (uint16_t)(rsp[1] | ((uint16_t)rsp[2] << 8));
      cyc_us = rsp[6] ? rsp[6] : 240U;
      fill = (uint16_t)snprintf(chunk, sizeof chunk, "HSDIREC n=%u mask=0x%02x cyc_us=%lu lim=%u\n",
                                (unsigned)n, rsp[5], (unsigned long)cyc_us, (unsigned)(rsp[3] | ((uint16_t)rsp[4] << 8)));
    }
  }
  while (idx < n)
  {
    uint8_t req[5] = { 0x12U, 2U, (uint8_t)(idx & 0xFFU), (uint8_t)(idx >> 8), 60U };
    uint16_t r = app_rpc_transact(req, 5, rsp, sizeof rsp, 200), got = (uint16_t)(r / 8U);
    if (got == 0U) { if (++fails > 5U) { break; } vTaskDelay(pdMS_TO_TICKS(50)); continue; }
    fails = 0;
    for (uint16_t k = 0; k < got; k++)
    {
      const uint8_t *e = &rsp[8U * k];
      uint32_t ts = (uint32_t)e[0] | ((uint32_t)e[1] << 8) | ((uint32_t)e[2] << 16) | ((uint32_t)e[3] << 24);
      uint16_t ccr = (uint16_t)(e[4] | ((uint16_t)e[5] << 8));
      uint32_t d, us, frac;
      char ln[40];
      int ll;
      if (first) { t0 = ts; first = 0; }
      d = ts - t0; us = d / cyc_us; frac = ((d % cyc_us) * 1000U) / cyc_us;
      ll = snprintf(ln, sizeof ln, "%lu.%03lu,%u,%u,%u,%u\n", (unsigned long)us, (unsigned long)frac,
                    (unsigned)(e[6] & 7U), (unsigned)((e[6] >> 4) & 1U), (unsigned)ccr, (unsigned)e[7]);
      if ((fill + (uint16_t)ll) > sizeof chunk) { rec_send(chunk, fill, seq++); fill = 0; }
      memcpy(&chunk[fill], ln, (size_t)ll); fill = (uint16_t)(fill + (uint16_t)ll);
    }
    idx = (uint16_t)(idx + got);
  }
  if ((fill + 4U) > sizeof chunk) { rec_send(chunk, fill, seq++); fill = 0; }
  memcpy(&chunk[fill], "END\n", 4); fill = (uint16_t)(fill + 4U);
  rec_send(chunk, fill, seq++);
  s_rec_task = NULL;
  vTaskDelete(NULL);
}

int app_hsdi_cmd(const char *line, const char *src, char *out, uint16_t cap)
{
  extern uint16_t app_rpc_transact(const uint8_t *, uint16_t, uint8_t *, uint16_t, uint32_t);
  (void)src;
  if (strncmp(line, "hsdi ", 5) != 0) { return 0; }
  if (strncmp(line + 5, "rec", 3) == 0)            /* edge recorder: rec <mask|all> [n] | rec stat | rec get */
  {
    const char *a = line + 8;
    while (*a == ' ') { a++; }
    if (strncmp(a, "get", 3) == 0)
    {
      if (s_rec_task != NULL) { snprintf(out, cap, "hsdi rec get: busy"); return 1; }
      s_rec_chunks = 0;
      if (xTaskCreate(rec_dump_task, "hsdirec", 1024, NULL, tskIDLE_PRIORITY + 1, &s_rec_task) != pdPASS)
      { snprintf(out, cap, "hsdi rec get: no task"); return 1; }
      snprintf(out, cap, "hsdi rec get: streaming to up/hsdirec/<seq>");
      return 1;
    }
    if (strncmp(a, "stat", 4) != 0)                /* anything else = arm: <mask hex | all> [n] */
    {
      unsigned mask = (strncmp(a, "all", 3) == 0) ? 0xFFU : (unsigned)strtoul(a, NULL, 16);
      const char *h = strchr(a, ' ');
      unsigned lim = (h != NULL) ? (unsigned)atoi(h + 1) : 0U;
      uint8_t req[5] = { 0x12U, 0U, (uint8_t)mask, (uint8_t)(lim & 0xFFU), (uint8_t)(lim >> 8) }, rsp[8];
      if (app_rpc_transact(req, 5, rsp, sizeof rsp, 100) != 8U) { snprintf(out, cap, "hsdi rec: no reply"); return 1; }
    }
    {
      uint8_t req[2] = { 0x12U, 1U }, rsp[8];
      if (app_rpc_transact(req, 2, rsp, sizeof rsp, 100) != 8U) { snprintf(out, cap, "hsdi rec: no reply"); return 1; }
      snprintf(out, cap, "rec armed=%u n=%u lim=%u mask=0x%02x cyc_us=%u chunks_sent=%u", rsp[0],
               (unsigned)(rsp[1] | ((uint16_t)rsp[2] << 8)), (unsigned)(rsp[3] | ((uint16_t)rsp[4] << 8)),
               rsp[5], rsp[6], (unsigned)s_rec_chunks);
    }
    return 1;
  }
  int ch = atoi(line + 5);
  const char *m = strchr(line + 5, ' ');
  if ((ch < 0) || (ch > 7) || (m == NULL))
  {
    snprintf(out, cap, "hsdi <0..7> off|di|sw [min_us]|hw [icf]|poll|cap [icf] [min_us]|stat ; hsdi rec <mask|all> [n]|stat|get");
    return 1;
  }
  m++;
  if (strncmp(m, "stat", 4) == 0)            /* channel signal forensics (CM4 op 0x11) */
  {
    uint8_t req[2] = { 0x11U, (uint8_t)ch }, rsp[56];
    uint32_t v[13];
    if (app_rpc_transact(req, 2, rsp, sizeof rsp, 100) != 52U) { snprintf(out, cap, "hsdi stat: no reply"); return 1; }
    memcpy(v, rsp, sizeof v);
    snprintf(out, cap, "h%d cnt=%lu poll=%lu hi=%lu min=%luus dt<100us:%lu <1ms:%lu <5ms:%lu >5ms:%lu rej=%lu coinc=%lu blip=%lu storm=%lu isrmax=%lu.%02luus",
             ch, (unsigned long)v[0], (unsigned long)v[1], (unsigned long)v[2], (unsigned long)v[3],
             (unsigned long)v[4], (unsigned long)v[5], (unsigned long)v[6], (unsigned long)v[7],
             (unsigned long)v[8], (unsigned long)v[9], (unsigned long)v[10], (unsigned long)v[11],
             (unsigned long)(v[12] / 100U), (unsigned long)(v[12] % 100U));
    return 1;
  }
  app_hsdi_ch_t saved = s_hsdi_table[ch];
  app_hsdi_ch_t *c = &s_hsdi_table[ch];
  const char *a1 = strchr(m, ' ');                 /* optional numeric arguments after the mode word */
  const char *a2 = (a1 != NULL) ? strchr(a1 + 1, ' ') : NULL;
  if      (strncmp(m, "off", 3) == 0)  { c->mode = APP_HSDI_OFF; }
  else if (strncmp(m, "di", 2) == 0)   { c->mode = APP_HSDI_DI; c->debounce_ms = 10; }
  else if (strncmp(m, "sw", 2) == 0)   { c->mode = APP_HSDI_COUNT_SW; c->edge = APP_HSDI_EDGE_RISING; c->debounce_ms = 0;
                                         c->min_us = (a1 != NULL) ? (uint16_t)atoi(a1 + 1) : 0U; }
  else if (strncmp(m, "hw", 2) == 0)   { c->mode = APP_HSDI_COUNT_HW; c->edge = APP_HSDI_EDGE_RISING;
                                         c->filter = (a1 != NULL) ? (uint8_t)atoi(a1 + 1) : 15U; }
  else if (strncmp(m, "poll", 4) == 0) { c->mode = APP_HSDI_COUNT_POLL; c->edge = APP_HSDI_EDGE_RISING; c->debounce_ms = 0; }
  else if (strncmp(m, "cap", 3) == 0)  { c->mode = APP_HSDI_COUNT_CAP; c->edge = APP_HSDI_EDGE_RISING; c->debounce_ms = 0;
                                         c->filter = (a1 != NULL) ? (uint8_t)atoi(a1 + 1) : 15U;
                                         c->min_us = (a2 != NULL) ? (uint16_t)atoi(a2 + 1) : 1000U; }
  else { snprintf(out, cap, "hsdi: mode off|di|sw|hw|poll|cap|stat"); return 1; }
  {
    int rc = app_hsdi_setup(s_hsdi_table);
    if (rc != 0) { s_hsdi_table[ch] = saved; (void)app_hsdi_setup(s_hsdi_table); snprintf(out, cap, "hsdi: rejected (%d), restored", rc); return 1; }
  }
  snprintf(out, cap, "hsdi%d mode=%u filter=%u min_us=%u applied", ch, (unsigned)c->mode, (unsigned)c->filter, (unsigned)c->min_us);
  return 1;
}
int app_pulse_cli(char *l)  /* USB console entry: pulse / hsdi <ch> <mode> */
{
  char out[96];
  if (app_pulse_cmd(l, "cli", out, sizeof out) || app_hsdi_cmd(l, "cli", out, sizeof out)) { printf("%s\n\r", out); return 1; }
  return 0;
}

/* ---- water flow meter on HSDI0 (2026-08-31): pulse flowmeter, 660 pulses per liter ----
 * The hardware counter does all the counting; this is only engineering conversion.
 * Total = pulses since boot (resets with the board; the dashboard history keeps the
 * long-term record). Rate = lazy >=30 s window, refreshed by the 5 s heartbeat caller. */
#define FLOW_PPL 660UL

/* Top-up episode journaling (2026-09-02 user ruling "if the meter turns, record it"):
 * the float valve announces itself through the meter, so the METER writes the ledger —
 * ground truth the dashboard's EC-drop guesser never had (that morning's pair: a real
 * 2.5 L top-up and a calibration artifact looked identical in EC). An episode opens on
 * the first pulse, closes after 60 s without one, and journals a single NOTE with the
 * volume; blips under 0.2 L are discarded. A reboot mid-fill loses that episode (the
 * hardware counter restarts) — the flow column in the sample table still shows it. */
static void flow_topup_poll(uint32_t cnt)  /* called every control tick (20 ms) */
{
  static uint32_t ep_start, last_cnt, quiet_ms, ep_ms;
  static uint8_t  in_ep, primed;
  uint32_t d;
  if (!primed) { primed = 1U; last_cnt = cnt; return; }
  d = cnt - last_cnt;
  last_cnt = cnt;
  if (!in_ep)
  {
    if (d != 0U) { in_ep = 1U; ep_start = cnt - d; quiet_ms = 0U; ep_ms = 0U; }
    return;
  }
  ep_ms += 20U;
  quiet_ms = (d != 0U) ? 0U : (quiet_ms + 20U);
  if (quiet_ms >= 60000U)                  /* valve quiet a full minute: episode over */
  {
    uint32_t dl  = (uint32_t)((uint64_t)(cnt - ep_start) * 10ULL / FLOW_PPL);
    uint32_t min = (ep_ms - quiet_ms + 30000U) / 60000U;
    if (dl >= 2U)                          /* < 0.2 L = stray pulses, not a fill */
    {
      app_log_event("NOTE", "top-up %lu.%luL (meter %lumin)",
                    (unsigned long)(dl / 10U), (unsigned long)(dl % 10U), (unsigned long)min);
    }
    in_ep = 0U;
  }
}

uint32_t app_flow_dl(void)                 /* total since boot, 0.1 L units (datalog column, reboot marker) */
{
  return (uint32_t)((uint64_t)app_hsdi_count(0) * 10ULL / FLOW_PPL);
}
uint16_t app_flow_rate_dlmin(void)         /* rate, 0.1 L/min units */
{
  static uint32_t last_cnt = 0, last_tick = 0;
  static uint16_t rate = 0;
  static uint8_t  primed = 0;
  uint32_t now = xTaskGetTickCount();      /* 1 kHz tick = ms */
  uint32_t cnt = app_hsdi_count(0);
  if (!primed) { primed = 1; last_cnt = cnt; last_tick = now; return 0; }
  uint32_t el = now - last_tick;
  if (el >= 30000U)
  {
    uint32_t d = cnt - last_cnt;
    rate = (uint16_t)((uint64_t)d * 600000ULL / (FLOW_PPL * (uint64_t)el));
    last_cnt = cnt; last_tick = now;
  }
  return rate;
}
/* ---- per-gutter hall flow meters (2026-09-03): 1200 pulses per liter, one per NFT feed line.
 * Same engineering as the water meter: total = pulses since boot, rate = lazy >=30 s window
 * refreshed by the heartbeat caller. Gutter -> channel map lives here (gutter 2 moved from
 * HSDI5 to HSDI2 the same evening, see the HSDI table). */
#define GUTTER_PPL 1200UL
static const uint8_t s_gutter_ch[4] = { 4, 5, 6, 7 };
uint32_t app_gutter_total_dl(uint8_t g)    /* total since boot, 0.1 L units */
{
  return (g < 4U) ? (uint32_t)((uint64_t)app_hsdi_count(s_gutter_ch[g]) * 10ULL / GUTTER_PPL) : 0U;
}
uint16_t app_gutter_rate_dlmin(uint8_t g)  /* rate, 0.1 L/min units */
{
  static uint32_t last_cnt[4], last_tick[4];
  static uint16_t rate[4];
  static uint8_t  primed[4];
  if (g >= 4U) { return 0; }
  uint32_t now = xTaskGetTickCount();
  uint32_t cnt = app_hsdi_count(s_gutter_ch[g]);
  if (!primed[g]) { primed[g] = 1; last_cnt[g] = cnt; last_tick[g] = now; return 0; }
  uint32_t el = now - last_tick[g];
  if (el >= 30000U)
  {
    uint32_t d = cnt - last_cnt[g];
    uint64_t r = (uint64_t)d * 600000ULL / (GUTTER_PPL * (uint64_t)el);
    /* plausibility cap (2026-09-03 evening, gutter 3 clogged): an impeller stalled on a
     * magnetic edge parks the hall output at threshold and the front-end Schmitt gate
     * self-oscillates — the hardware counter swallowed ~1 kHz of "pulses" on a line with
     * no flow at all. A feed line cannot exceed 30 L/min; anything above is noise and is
     * reported as 0, which is also the honest reading for a clogged gutter. */
    rate[g] = (r > 300ULL) ? 0U : (uint16_t)r;
    last_cnt[g] = cnt; last_tick[g] = now;
  }
  return rate[g];
}
uint16_t app_demo_relays(void)             /* TRUE relay state, read back from the module (FC01) */
{
  uint16_t m = 0;
  for (uint8_t i = 0; i < 16U; i++) { if (app_io_di(PT_RELAY_RB, i)) { m |= (uint16_t)(1U << i); } }
  return m;
}
void app_demo_relay_set(uint16_t mask)     /* dashboard writes the whole 16-bit relay bitmap */
{
  for (uint8_t i = 0; i < 16U; i++) { app_io_do_set(PT_RELAY, i, (uint8_t)((mask >> i) & 1U)); }
}

/* ==========================================================================================
 * 3. STARTUP — generic wiring, driven entirely by the tables above
 * ========================================================================================== */
void app_user_init(void)
{
  /* the port the field devices sit on, as a Modbus master */
  app_mbport_configure(CFG_FIELD_PORT, APP_MB_MASTER, CFG_FIELD_BAUD, 'N', 1, 0);

  /* hand the tables to the platform (1 = 1 ms scan base tick) */
  app_io_setup(s_io_table, (uint16_t)(sizeof(s_io_table) / sizeof(s_io_table[0])), 1);
  app_hsdi_setup(s_hsdi_table);

  /* OPTIONAL: expose everything above to an HMI / SCADA / PLC. Setting another port to Modbus
   * slave turns this board into a data concentrator — no extra code. Modbus TCP over Ethernet
   * serves the identical map at the identical addresses. Run 'pio dump' on the USB console to
   * print the external address of every point for whoever integrates the HMI. */
  app_mbport_configure(CFG_HMI_PORT, APP_MB_SLAVE, CFG_FIELD_BAUD, 'N', 1, CFG_HMI_ADDR);

  /* your task(s). Stack size is in WORDS (1024 words = 4 KB). */
  xTaskCreate(control_task, "ctrl", 1024, NULL, APP_TASK_PRIO_NORMAL, NULL);

  /* greenhouse roof-vent temperature control (app_vent.c): three-stage window on
   * relay coils 13..15, air temperature from PT_PHEC. "vent" on CLI/cloud to override. */
  app_vent_init();

  /* nutrient/pH dosing (app_dose.c): three peristaltic pumps on relay coils 0..2,
   * EC/pH from PT_PHEC. Boots in OFF (pumps held off) — "dose" on CLI/cloud to operate. */
  app_dose_init();

  /* per-gutter feed-flow monitor (app_flowmon.c): a gutter whose feed flow stays below
   * 1.2 L/min for 2 min is probably blocked -> FAULT event + live cloud alarm (phone push
   * via the dashboard) + optional buzzer chirp. "flow" on CLI/cloud to tune / silence. */
  app_flowmon_init();

  /* reservoir aeration (app_aer.c): air pump on relay coil 8 (O9), on above a settable
   * water temperature (default 22.0 C, 1.0 C hysteresis), water temps from PT_PHEC. Boots
   * in auto, so a reset re-derives the pump state instead of leaving it silently off.
   * "aer" on CLI/cloud to set the temperature or override. */
  app_aer_init();

  /* For one-off / aperiodic access (setup, diagnostics, OTA) the blocking app_mb_read/write_*
   * helpers in app_platform.h are still the right tool — the process image is for cyclic I/O. */
}
